<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WS_BPEL_Checkout" targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout" xmlns:ns="http://xml.netbeans.org/schema/UserSchema" xmlns:ns0="http://xml.netbeans.org/schema/cameraResponse" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout">
            <xsd:import namespace="http://xml.netbeans.org/schema/UserSchema" schemaLocation="UserSchema.xsd"/>
            <xsd:import namespace="http://xml.netbeans.org/schema/cameraResponse" schemaLocation="CameraResponse.xsd"/>
        </xsd:schema>
    </types>
    <message name="WS_BPEL_CheckoutOperationRequest">
        <part name="userInput" type="ns:user"/>
        <part name="camerasInput" type="ns0:searchCamerasResponse"/>
    </message>
    <message name="WS_BPEL_CheckoutOperationResponse">
        <part name="resultOutput" type="xsd:boolean"/>
    </message>
    <portType name="WS_BPEL_CheckoutPortType">
        <operation name="WS_BPEL_CheckoutOperation">
            <input name="input1" message="tns:WS_BPEL_CheckoutOperationRequest"/>
            <output name="output1" message="tns:WS_BPEL_CheckoutOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="WS_BPEL_Checkout">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WS_BPEL_CheckoutPortTypeRole" portType="tns:WS_BPEL_CheckoutPortType"/>
    </plnk:partnerLinkType>
</definitions>
