<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WS_BPEL_Checkout" targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout" xmlns:ns="http://xml.netbeans.org/schema/Purchases" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Checkout">
            <xsd:import namespace="http://xml.netbeans.org/schema/Purchases" schemaLocation="Purchases.xsd"/>
        </xsd:schema>
    </types>
    <message name="WS_BPEL_CheckoutOperationRequest">
        <part name="CheckoutRequest" element="ns:CheckoutRequest"/>
    </message>
    <message name="WS_BPEL_CheckoutOperationResponse">
        <part name="CheckoutResponse" element="ns:CheckoutResponse"/>
    </message>
    <portType name="WS_BPEL_CheckoutPortType">
        <operation name="WS_BPEL_CheckoutOperation">
            <input name="input1" message="tns:WS_BPEL_CheckoutOperationRequest"/>
            <output name="output1" message="tns:WS_BPEL_CheckoutOperationResponse"/>
        </operation>
    </portType>
    <binding name="WS_BPEL_CheckoutBinding" type="tns:WS_BPEL_CheckoutPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="WS_BPEL_CheckoutOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal"/>
            </input>
            <output name="output1">
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="WS_BPEL_CheckoutService">
        <port name="WS_BPEL_CheckoutPort" binding="tns:WS_BPEL_CheckoutBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/WS_BPEL_CheckoutService/WS_BPEL_CheckoutPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="WS_BPEL_Checkout">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WS_BPEL_CheckoutPortTypeRole" portType="tns:WS_BPEL_CheckoutPortType"/>
    </plnk:partnerLinkType>
</definitions>
