<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WS_BPEL_Shipped" targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Shipped"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Shipped" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types/>
    <message name="WS_BPEL_ShippedOperationRequest">
        <part name="orderId" type="xsd:int"/>
        <part name="shippedDates" type="xsd:string"/>
    </message>
    <portType name="WS_BPEL_ShippedPortType">
        <operation name="WS_BPEL_ShippedOperation">
            <input name="input1" message="tns:WS_BPEL_ShippedOperationRequest"/>
        </operation>
    </portType>
    <binding name="WS_BPEL_ShippedBinding" type="tns:WS_BPEL_ShippedPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="WS_BPEL_ShippedOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BPEL_Purchases/WS_BPEL_Shipped"/>
            </input>
        </operation>
    </binding>
    <service name="WS_BPEL_ShippedService">
        <port name="WS_BPEL_ShippedPort" binding="tns:WS_BPEL_ShippedBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/WS_BPEL_ShippedService/WS_BPEL_ShippedPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="WS_BPEL_Shipped">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WS_BPEL_ShippedPortTypeRole" portType="tns:WS_BPEL_ShippedPortType"/>
    </plnk:partnerLinkType>
</definitions>
