<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WS_BPELSearchCameras" targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_SearchCameras/WS_BPELSearchCameras"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/BPEL_SearchCameras/WS_BPELSearchCameras" xmlns:ns="http://xml.netbeans.org/schema/cameraResponse" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/BPEL_SearchCameras/WS_BPELSearchCameras">
            <xsd:import namespace="http://xml.netbeans.org/schema/cameraResponse" schemaLocation="CameraResponse.xsd"/>
        </xsd:schema>
    </types>
    <message name="WS_BPELSearchCamerasOperationRequest">
        <part name="part1" type="xsd:string"/>
    </message>
    <message name="WS_BPELSearchCamerasOperationResponse">
        <part name="camerasOutput" element="ns:SearchCameraInput"/>
    </message>
    <portType name="WS_BPELSearchCamerasPortType">
        <operation name="WS_BPELSearchCamerasOperation">
            <input name="input1" message="tns:WS_BPELSearchCamerasOperationRequest"/>
            <output name="output1" message="tns:WS_BPELSearchCamerasOperationResponse"/>
        </operation>
    </portType>
    <binding name="WS_BPELSearchCamerasBinding" type="tns:WS_BPELSearchCamerasPortType">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="WS_BPELSearchCamerasOperation">
            <soap:operation/>
            <input name="input1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BPEL_SearchCameras/WS_BPELSearchCameras"/>
            </input>
            <output name="output1">
                <soap:body use="literal" namespace="http://j2ee.netbeans.org/wsdl/BPEL_SearchCameras/WS_BPELSearchCameras"/>
            </output>
        </operation>
    </binding>
    <service name="WS_BPELSearchCamerasService">
        <port name="WS_BPELSearchCamerasPort" binding="tns:WS_BPELSearchCamerasBinding">
            <soap:address location="http://localhost:${HttpDefaultPort}/WS_BPELSearchCamerasService/WS_BPELSearchCamerasPort"/>
        </port>
    </service>
    <plnk:partnerLinkType name="WS_BPELSearchCameras">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="WS_BPELSearchCamerasPortTypeRole" portType="tns:WS_BPELSearchCamerasPortType"/>
    </plnk:partnerLinkType>
</definitions>
