<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSCameraSupplierWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSCameraSupplierWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSCameraSupplierWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://cs.eai.dei.uc.pt/">
    <import location="127.0.0.1_8080/WSCameraSupplier.wsdl" namespace="http://cs.eai.dei.uc.pt/"/>
    <plnk:partnerLinkType name="CameraSupplierLinkType">
        <plnk:role name="CameraSupplierRole" portType="ns:CameraSupplier"/>
    </plnk:partnerLinkType>
</definitions>
