<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WSCatalogCenterWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WSCatalogCenterWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WSCatalogCenterWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://cc.eai.dei.uc.pt/">
    <import location="127.0.0.1_8080/WSCatalogCenter.wsdl" namespace="http://cc.eai.dei.uc.pt/"/>
    <plnk:partnerLinkType name="CatalogCenterLinkType">
        <plnk:role name="CatalogCenterRole" portType="ns:CatalogCenter"/>
    </plnk:partnerLinkType>
</definitions>
